=== Luceium/CS157A/hw4/buildings.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" fullyQualified="true">
    <xs:element name="Buildings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Building" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:all minOccurs="1">
                            <!-- Elements -->
                            <!-- Position -->
                            <xs:element name="Position">
                                <xs:complexType>
                                    <xs:all minOccurs="1">
                                        <xs:element name="Latitude" type="xs:decimal" />
                                        <xs:element name="Longitude" type="xs:decimal" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            
                            <!-- Address: optional, includes StreetNo, StreetName, City, State, Zip -->
                            <xs:element name="Address" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="StreetNo" type="xs:string" />
                                    <xs:attribute name="StreetName" type="xs:string" />
                                    <xs:attribute name="City" type="xs:string" />
                                    <xs:attribute name="State" type="xs:string" />
                                    <xs:attribute name="Zip" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                
                            <!-- BuildingCode -->
                            <!-- Would have been an attribute but, it's used multiple times in students -->
                            <b:Buildings name="BuildingCode" type="BuildingCodeType" />
                        </xs:all>
                        
                        <!-- Attributes (useful bc 1 instance is already handled) -->
                    
                        <!-- BuildingName -->
                        <xs:attribute name="BuildingName" use="required" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Define BuildingCode type in gloabal to make it accessable to stuent.xsd -->
    <xs:simpleType name="BuildingCodeType">
        <xs:restriction base="xs:string">
            <xs:length value="3" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Luceium/CS157A/hw4/buildings.xml
<?xml version="1.0" encoding="utf-8"?>

<Buildings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="buildings.xsd">
    <Building BuildingName="King Olympic Hall">
        <BuildingCode>KOH</BuildingCode>
        <Position>
            <Latitude>34.024547</Latitude>
            <Longitude>-118.288</Longitude>
        </Position>
        <Address StreetNo="1027" StreetName="W 34th St" City="Los Angeles" State="CA" Zip="90007"/>
    </Building>
    <Building BuildingName="Cromwell Field">
        <BuildingCode>CFX</BuildingCode>
        <Position>
            <Latitude>34.021631</Latitude>
            <Longitude>-118.289</Longitude>
        </Position>
        <Address StreetNo="1026" StreetName="W 34th St" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="JEP House">
        <BuildingCode>JEP</BuildingCode>
        <Position>
            <Latitude>34.022947</Latitude>
            <Longitude>-118.284</Longitude>
        </Position>
        <Address StreetNo="801" StreetName="W 34th St" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Student Health Center">
        <BuildingCode>SHC</BuildingCode>
        <Position>
            <Latitude>34.023303</Latitude>
            <Longitude>-118.285</Longitude>
        </Position>
        <Address StreetNo="849" StreetName="W 34th St" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Leavey Library">
        <BuildingCode>LVY</BuildingCode>
        <Position>
            <Latitude>34.021595</Latitude>
            <Longitude>-118.282</Longitude>
        </Position>
        <Address StreetNo="651" StreetName="W 35th St" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Von KleinSmid Center">
        <BuildingCode>VKC</BuildingCode>
        <Position>
            <Latitude>34.021649</Latitude>
            <Longitude>-118.284</Longitude>
        </Position>
        <Address StreetNo="3518" StreetName="Trousdale" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Waite Phillips Hall">
        <BuildingCode>WPH</BuildingCode>
        <Position>
            <Latitude>34.022289</Latitude>
            <Longitude>-118.284</Longitude>
        </Position>
        <Address StreetNo="3550" StreetName="Trousdale" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="John Hubbard Hall">
        <BuildingCode>JHH</BuildingCode>
        <Position>
            <Latitude>34.020101</Latitude>
            <Longitude>-118.284</Longitude>
        </Position>
        <Address StreetNo="615" StreetName="Childs Way" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Registration Building">
        <BuildingCode>REG</BuildingCode>
        <Position>
            <Latitude>34.019603</Latitude>
            <Longitude>-118.282</Longitude>
        </Position>
        <Address StreetNo="611" StreetName="Childs Way" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Student Union">
        <BuildingCode>STU</BuildingCode>
        <Position>
            <Latitude>34.020226</Latitude>
            <Longitude>-118.286</Longitude>
        </Position>
        <Address StreetNo="3551" StreetName="Trousdale" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Bookstore">
        <BuildingCode>BKS</BuildingCode>
        <Position>
            <Latitude>34.020635</Latitude>
            <Longitude>-118.286</Longitude>
        </Position>
        <Address StreetNo="840" StreetName="Childs Way" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Ronald Tutor Hall">
        <BuildingCode>RTH</BuildingCode>
        <Position>
            <Latitude>34.020137</Latitude>
            <Longitude>-118.29</Longitude>
        </Position>
        <Address StreetNo="3710" StreetName="McClintock" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Salvatori Com. Center">
        <BuildingCode>SAL</BuildingCode>
        <Position>
            <Latitude>34.01955</Latitude>
            <Longitude>-118.289</Longitude>
        </Position>
        <Address StreetNo="941" StreetName="W 37th Place" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Electrical Engr Center">
        <BuildingCode>EEB</BuildingCode>
        <Position>
            <Latitude>34.019728</Latitude>
            <Longitude>-118.29</Longitude>
        </Position>
        <Address StreetNo="3715" StreetName="McClintock" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
    <Building BuildingName="Olin Hall Engineering">
        <BuildingCode>OHE</BuildingCode>
        <Position>
            <Latitude>34.020493</Latitude>
            <Longitude>-118.29</Longitude>
        </Position>
        <Address StreetNo="3650" StreetName="McClintock" City="Los Angeles" State="CA" Zip="90089"/>
    </Building>
</Buildings>
